[scenario]
name = "small-trace"

[venvs]
python = ["2.7", "3.7"]
ddtrace = ["0.46.0", "0.47.0"]
# python = ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
# ddtrace = ["0.40.0", "0.41.0", "0.42.0", "0.43.0", "0.44.0", "0.45.0", "0.46.0", "0.47.0"]
